export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST";
export const ADD_USERS_SUCCESS = "ADD_USERS_SUCESS";

export const GET_SINGLE_USERS = "GET_SINGLE_USERS";

export const DELETE_USERS_REQUEST = "DELETE_USERS_REQUESTS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";

export const EDIT_USERS_REQUEST = "EDIT_USERS_REQUEST";
export const EDIT_USERS_SUCCESS = "EDIT_USERS_SUCCESS";

export const GET_EDIT_OF_SINGLE_REQUEST = "GET_EDIT_OF_SINGLE_REQUEST";
export const GET_EDIT_OF_SINGLE_SUCCESS = "GET_EDIT_OF_SINGLE_SUCCESS";


export const ADD_BLOG_DATA_REQUEST = "ADD_BLOG_DATA_REQUEST";
export const ADD_BLOG_DATA_SUCCESS = "ADD_BLOG_DATA_SUCCESS";

export const GET_BLOG_DATA_REQUEST = "GET_BLOG_DATA_REQUEST";
export const GET_BLOG_DATA_SUCCESS = "GET_BLOG_DATA_SUCCESS";

export const GET_BLOG_DATA_FAIL = "GET_BLOG_DATA_FAIL";
export const ADD_BLOG_DATA_FAIL = "ADD_BLOG_DATA_FAIL";

export const UPLOAD_IMAGES_REQUEST ="UPLOAD_IMAGES_REQUEST"
export const UPLOAD_IMAGES_SUCCESS="UPLOAD_IMAGES_SUCCESS"

export const GET_FILE_REQUEST = "GET_FILE_REQUEST";
export const GET_FILE_SUCCESS = "GET_FILE_SUCCESS";

