
export const GET_BLOG_DATA_REQUEST = "GET_BLOG_DATA_REQUEST";
export const GET_BLOG_DATA_SUCCESS = "GET_BLOG_DATA_SUCCESS";
export const GET_BLOG_DATA_FAIL = "GET_BLOG_DATA_FAIL";


export const CATEGORY_REQUEST = "CATEGORY_REQUEST"
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
export const CATEGORY_FAILURE = "CATEGORY_FAILURE"

export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";